### ISSUE TITLE
BuyPlayer table doesn't exist

### ISSUE THREAD

**Issue by josemprb** [jerustes/AW-threepointer#15]
causa raíz

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '17_appweb_10d.plantilla_deportista' doesn't exist
	sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	java.lang.reflect.Constructor.newInstance(Unknown Source)
	com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	com.mysql.jdbc.Util.getInstance(Util.java:408)
	com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
	com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)

causa raíz

org.hibernate.exception.SQLGrammarException: could not execute statement
	org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63)
	org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
	org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	org.hibernate.persister.collection.AbstractCollectionPersister.remove(AbstractCollectionPersister.java:1222)
	org.hibernate.action.internal.CollectionRemoveAction.execute(CollectionRemoveAction.java:96)
	org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:589)
	org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1437)
	org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:493)
	org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3207)
	org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2413)
	org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:467)
	org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:156)
	org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
	org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68)
	webapp.BuyPlayer.doGet(BuyPlayer.java:98)

In the line where it is the commit. So, it doesn't read correctly the name of plantilladeportista table, inserting a back slash in the middle.

**Comment by jerustes** [comment]
donete, if you agree
