### ISSUE TITLE
Lineup name

### ISSUE THREAD

**Issue by jerustes** [jerustes/AW-threepointer#8]
Vista LeagueHome: show lineups that conform that league with a name. Be this name user-guiding-the-team's name or a name for the actual lineup. Right now will show just some id but this needs fixing.

**Comment by josemprb** [comment]
There's no team for actual lineup. However, there's user name that could be used, but requires of accesing to all users, and that is another query, or trying a inner join.

**Comment by josemprb** [comment]
Solved!
