### ISSUE TITLE
LeagueHome Vista type mismatches

### ISSUE THREAD

**Issue by jerustes** [jerustes/AW-threepointer#9]
need to request some obj through the servlet (querys) as the attributes are an index and cannot access the obj they point to through jsp.

L21: creator int -> User
L22: lineupUser int -> User

**Comment by josemprb** [comment]
Queries done, solved!

**Comment by jerustes** [comment]
type Informe de Excepción

mensaje Ha sucedido una excepción al procesar la página JSP /LeagueHome.jsp en línea 36

descripción El servidor encontró un error interno que hizo que no pudiera rellenar este requerimiento.

excepción

org.apache.jasper.JasperException: Ha sucedido una excepción al procesar la página JSP /LeagueHome.jsp en línea 36

33: 		</thead>
34: 		<tbody>
35: 			<tr>
36: 				<td><%=currentUser.getName()%></td>
37: 				<td><%=lineupUser.getBalance() %></td>
38: 				<td><%=lineupUser.getTeamLineup() %></td>
39: 			</tr>


Stacktrace:
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:579)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
causa raíz

java.lang.NullPointerException
	org.apache.jsp.LeagueHome_jsp._jspService(LeagueHome_jsp.java:150)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by josemprb** [comment]
solved!!
